### ISSUE TITLE
About stdgpu::queue size < 0

### ISSUE THREAD

**Issue by yofufufufu** [stotko/stdgpu#396]
Hello, I found that sometimes `queue.size()` < 0, I guess it is because more than one  threads `pop` the empty queue at the same time.
I can see this warning when program running:
https://github.com/stotko/stdgpu/blob/d9a45876bf219f92b12f3d2d707f87d733a6ac30/src/stdgpu/impl/deque_detail.cuh#L434-L441
Even worse, I found that the queue will be **invalid**(`queue.valid()=false`) after the CUDA kernel, which causes unexpected result when I try to reuse it in another kernel like:
```
__global__ void kernel1(){
// push and pop operation
}

__global__ void kernel2(){
// push and pop operation
}

int main() {
kernel1<<<>>>(queue);
kernel2<<<>>>(queue);
}
```
What should I do? Thank in advance!

**Comment by stotko** [comment]
Like in the C++ standard library, calling `pop_front` or `pop_back` on an *empty* `stdgpu::deque` is **undefined behavior**, see for example https://en.cppreference.com/w/cpp/container/deque/pop_back. In stdgpu, we try to detect these cases and return a warning message as you have already observed. However due to parallelization, not all of these `pop_*` attempts can be reliably catched, so the size and, in turn, the state of `deque` may become invalid at some point.

The solution is to avoid calling `pop_*` on an empty `stdgpu::deque` in your kernel.

**Comment by stotko** [comment]
According to your code snippet, if the main purpose of the kernel is to iterate over all elements of the queue and then removing the element from the queue, then you could also use pass `auto queue_elements = queue.device_range()` to the kernel and afterwards perform `queue.clear()`. Alternatively, you could also query `queue.size()` beforehand and only call `pop_*` this number of times.

**Comment by yofufufufu** [comment]
Thanks for your help! I would carefully consider your suggestions.
